name: Python CI

on:
    push:
      branches: ["Main"]
    pull_request: 
      branches: ["Main"]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Check out repository
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install psutil
            pip install pytest
            pip install keyboard
            
        - name: Run tests
          run: |
            pytest

